/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolabinn;

import ConexiónDB.CheckConnection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectolabinn.Clases.Categoria;

/**
 *
 * @author Ale
 */
public class Form_onlyTests extends javax.swing.JFrame {

    /**
     * Creates new form Form_onlyTests
     */
    public Form_onlyTests() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jF_VerProductos = new javax.swing.JFrame();
        jLabel_listaTallas = new javax.swing.JLabel();
        JScrollPane4 = new javax.swing.JScrollPane();
        tblListaProductos = new javax.swing.JTable();
        btnNuevoProducto = new javax.swing.JButton();
        btnBorrarProducto = new javax.swing.JButton();
        jF_AñadirProductos = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jText_IDProducto = new javax.swing.JTextField();
        jText_proNombre = new javax.swing.JTextField();
        jText_proPrecio = new javax.swing.JTextField();
        jText_proTalla = new javax.swing.JTextField();
        jCBox_catNombre = new javax.swing.JComboBox();
        btnIngresarProducto = new javax.swing.JButton();
        btnCancelar_NuevoProd = new javax.swing.JButton();
        jF_VerCategorias = new javax.swing.JFrame();
        jLabel_listaTallas1 = new javax.swing.JLabel();
        JScrollPane5 = new javax.swing.JScrollPane();
        tblListaCategorias = new javax.swing.JTable();
        btnNuevaCategoria = new javax.swing.JButton();
        btnBorrarCategoria = new javax.swing.JButton();
        jF_AñadirCategoria = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jText_IDCategoria = new javax.swing.JTextField();
        jText_catNombre = new javax.swing.JTextField();
        btn_IngresarCategoria = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jF_VerProveedores = new javax.swing.JFrame();
        jLabel_listaProveedores = new javax.swing.JLabel();
        JScrollPane6 = new javax.swing.JScrollPane();
        tblListaProveedores = new javax.swing.JTable();
        btnNuevoProveedor = new javax.swing.JButton();
        btnBorrarProveedor = new javax.swing.JButton();
        jF_AñadirProveedores = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jText_IDnewProveedor = new javax.swing.JTextField();
        jText_provNombre = new javax.swing.JTextField();
        jText_provContacto = new javax.swing.JTextField();
        jText_provNotas = new javax.swing.JTextField();
        btnIngresarProveedor = new javax.swing.JButton();
        btnCancelar_Nuevoprov = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnVerProductos = new javax.swing.JButton();
        btnVerCategorias = new javax.swing.JButton();
        btnVerProveedores = new javax.swing.JButton();
        btnVerSucursales = new javax.swing.JButton();
        btnVerUsuarios = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jF_VerProductos.setMinimumSize(new java.awt.Dimension(750, 300));

        jLabel_listaTallas.setText("Lista de Productos");

        tblListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", " ", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JScrollPane4.setViewportView(tblListaProductos);

        btnNuevoProducto.setText("Nuevo Producto");
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });

        btnBorrarProducto.setText("Eliminar Producto");
        btnBorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jF_VerProductosLayout = new javax.swing.GroupLayout(jF_VerProductos.getContentPane());
        jF_VerProductos.getContentPane().setLayout(jF_VerProductosLayout);
        jF_VerProductosLayout.setHorizontalGroup(
            jF_VerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_VerProductosLayout.createSequentialGroup()
                .addGroup(jF_VerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jF_VerProductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jF_VerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jF_VerProductosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jF_VerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBorrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(JScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jF_VerProductosLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel_listaTallas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jF_VerProductosLayout.setVerticalGroup(
            jF_VerProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_VerProductosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel_listaTallas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevoProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrarProducto)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jF_AñadirProductos.setMinimumSize(new java.awt.Dimension(570, 250));

        jLabel2.setText("Añadir Nuevo Producto");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ID Producto:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Precio :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Categoria:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Talla : ");

        jText_IDProducto.setEditable(false);
        jText_IDProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jText_proNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jText_proPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jText_proTalla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnIngresarProducto.setText("Añadir");
        btnIngresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProductoActionPerformed(evt);
            }
        });

        btnCancelar_NuevoProd.setText("Cancelar");
        btnCancelar_NuevoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_NuevoProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jF_AñadirProductosLayout = new javax.swing.GroupLayout(jF_AñadirProductos.getContentPane());
        jF_AñadirProductos.getContentPane().setLayout(jF_AñadirProductosLayout);
        jF_AñadirProductosLayout.setHorizontalGroup(
            jF_AñadirProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_AñadirProductosLayout.createSequentialGroup()
                .addGroup(jF_AñadirProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jF_AñadirProductosLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel2))
                    .addGroup(jF_AñadirProductosLayout.createSequentialGroup()
                        .addGroup(jF_AñadirProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jF_AñadirProductosLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jText_proNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jF_AñadirProductosLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jText_proPrecio))
                            .addGroup(jF_AñadirProductosLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBox_catNombre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jF_AñadirProductosLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jF_AñadirProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jText_proTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIngresarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jF_AñadirProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jF_AñadirProductosLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jText_IDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jF_AñadirProductosLayout.createSequentialGroup()
                                .addComponent(btnCancelar_NuevoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jF_AñadirProductosLayout.setVerticalGroup(
            jF_AñadirProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_AñadirProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jF_AñadirProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jF_AñadirProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jText_IDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jF_AñadirProductosLayout.createSequentialGroup()
                        .addGroup(jF_AñadirProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jText_proNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jF_AñadirProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jText_proPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jF_AñadirProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBox_catNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jF_AñadirProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_proTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jF_AñadirProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarProducto)
                    .addComponent(btnCancelar_NuevoProd))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jF_VerCategorias.setMinimumSize(new java.awt.Dimension(750, 300));

        jLabel_listaTallas1.setText("Lista de Categorias");

        tblListaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JScrollPane5.setViewportView(tblListaCategorias);

        btnNuevaCategoria.setText("Nuevo Categoria");
        btnNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCategoriaActionPerformed(evt);
            }
        });

        btnBorrarCategoria.setText("Eliminar Categoria");
        btnBorrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jF_VerCategoriasLayout = new javax.swing.GroupLayout(jF_VerCategorias.getContentPane());
        jF_VerCategorias.getContentPane().setLayout(jF_VerCategoriasLayout);
        jF_VerCategoriasLayout.setHorizontalGroup(
            jF_VerCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_VerCategoriasLayout.createSequentialGroup()
                .addGroup(jF_VerCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jF_VerCategoriasLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jF_VerCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrarCategoria)))
                    .addGroup(jF_VerCategoriasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jF_VerCategoriasLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel_listaTallas1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jF_VerCategoriasLayout.setVerticalGroup(
            jF_VerCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_VerCategoriasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel_listaTallas1)
                .addGap(18, 18, 18)
                .addComponent(JScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevaCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrarCategoria)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jF_AñadirCategoria.setMinimumSize(new java.awt.Dimension(490, 330));

        jLabel11.setText("Añadir Nueva Categoria");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("ID Producto:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Nombre:");

        jText_IDCategoria.setEditable(false);
        jText_IDCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jText_catNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_IngresarCategoria.setText("Añadir");
        btn_IngresarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarCategoriaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout jF_AñadirCategoriaLayout = new javax.swing.GroupLayout(jF_AñadirCategoria.getContentPane());
        jF_AñadirCategoria.getContentPane().setLayout(jF_AñadirCategoriaLayout);
        jF_AñadirCategoriaLayout.setHorizontalGroup(
            jF_AñadirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_AñadirCategoriaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jF_AñadirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jF_AñadirCategoriaLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jText_IDCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jF_AñadirCategoriaLayout.createSequentialGroup()
                        .addGroup(jF_AñadirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btn_IngresarCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jF_AñadirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jF_AñadirCategoriaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jText_catNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jF_AñadirCategoriaLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jF_AñadirCategoriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jF_AñadirCategoriaLayout.setVerticalGroup(
            jF_AñadirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_AñadirCategoriaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jF_AñadirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jText_IDCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jF_AñadirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_catNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(29, 29, 29)
                .addGroup(jF_AñadirCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_IngresarCategoria)
                    .addComponent(btnCancelar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jF_VerProveedores.setMinimumSize(new java.awt.Dimension(750, 300));

        jLabel_listaProveedores.setText("Lista de Proveedores");

        tblListaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JScrollPane6.setViewportView(tblListaProveedores);

        btnNuevoProveedor.setText("Nuevo Proveedor");
        btnNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProveedorActionPerformed(evt);
            }
        });

        btnBorrarProveedor.setText("Editar Proveedor");
        btnBorrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jF_VerProveedoresLayout = new javax.swing.GroupLayout(jF_VerProveedores.getContentPane());
        jF_VerProveedores.getContentPane().setLayout(jF_VerProveedoresLayout);
        jF_VerProveedoresLayout.setHorizontalGroup(
            jF_VerProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_VerProveedoresLayout.createSequentialGroup()
                .addGroup(jF_VerProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jF_VerProveedoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jF_VerProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jF_VerProveedoresLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jF_VerProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnNuevoProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBorrarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(JScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jF_VerProveedoresLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel_listaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jF_VerProveedoresLayout.setVerticalGroup(
            jF_VerProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_VerProveedoresLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel_listaProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevoProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrarProveedor)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jF_AñadirProveedores.setMinimumSize(new java.awt.Dimension(580, 270));

        jLabel17.setText("Añadir Nuevo Proveedor");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("ID Proveedor:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Nombre:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Contacto (Cel o Email):");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Notas (Comentario) : ");

        jText_IDnewProveedor.setEditable(false);
        jText_IDnewProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jText_provNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jText_provContacto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jText_provNotas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnIngresarProveedor.setText("Añadir");
        btnIngresarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProveedorActionPerformed(evt);
            }
        });

        btnCancelar_Nuevoprov.setText("Cancelar");
        btnCancelar_Nuevoprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_NuevoprovActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jF_AñadirProveedoresLayout = new javax.swing.GroupLayout(jF_AñadirProveedores.getContentPane());
        jF_AñadirProveedores.getContentPane().setLayout(jF_AñadirProveedoresLayout);
        jF_AñadirProveedoresLayout.setHorizontalGroup(
            jF_AñadirProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_AñadirProveedoresLayout.createSequentialGroup()
                .addGroup(jF_AñadirProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jF_AñadirProveedoresLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnIngresarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jF_AñadirProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jF_AñadirProveedoresLayout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jText_IDnewProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jF_AñadirProveedoresLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar_Nuevoprov, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(jF_AñadirProveedoresLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel17))
                    .addGroup(jF_AñadirProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jF_AñadirProveedoresLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jText_provNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jF_AñadirProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jF_AñadirProveedoresLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(jText_provNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jF_AñadirProveedoresLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jText_provContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jF_AñadirProveedoresLayout.setVerticalGroup(
            jF_AñadirProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_AñadirProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jF_AñadirProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jText_IDnewProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jF_AñadirProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jF_AñadirProveedoresLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jF_AñadirProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText_provNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jF_AñadirProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jText_provContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jF_AñadirProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText_provNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(112, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jF_AñadirProveedoresLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jF_AñadirProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIngresarProveedor)
                            .addComponent(btnCancelar_Nuevoprov))
                        .addGap(28, 28, 28))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Solo Tests");

        jTextField1.setText("jTextField1");

        btnVerProductos.setText("Ver Productos");
        btnVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProductosActionPerformed(evt);
            }
        });

        btnVerCategorias.setText("Ver Categorias");
        btnVerCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCategoriasActionPerformed(evt);
            }
        });

        btnVerProveedores.setText("Ver Proveedores");
        btnVerProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProveedoresActionPerformed(evt);
            }
        });

        btnVerSucursales.setText("Ver Sucursales");

        btnVerUsuarios.setText("Ver Usuarios");

        jButton4.setText("Ingresar Ventas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Ver Ventas");

        jButton6.setText("Devoluciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(btnVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnVerCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(btnVerSucursales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(537, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerProveedores)
                    .addComponent(btnVerSucursales))
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProductosActionPerformed
        jF_VerProductos.setVisible(true);
        jF_VerProductos.setLocationRelativeTo(null);
        
        CheckConnection con = new CheckConnection();
           try{ 
            DefaultTableModel tblVerProductos = new DefaultTableModel(); //Crear Modelo de Tabla
            tblListaProductos.setModel(tblVerProductos);  // Asignar el Modelo de Tabla 
 
            tblVerProductos.addColumn("IDProducto"); //Asigna nom,be a cada columna del Modelo de Tabla
            tblVerProductos.addColumn("Nombre");
            tblVerProductos.addColumn("Precio");
            tblVerProductos.addColumn("Categoría");
            tblVerProductos.addColumn("Talla");

     
            String query = "SELECT * FROM tblProductos";
                        
            ResultSet rsRV = EjecutarQuery(con, query);    

 
            while(rsRV.next())
            { //Extrae del rs y lo añade al Modelo de Tabla     
              tblVerProductos.addRow(new Object[] {rsRV.getString("IDProducto"),rsRV.getString("proNombre"),rsRV.getString("proPrecio"), 
                  rsRV.getString("IDCategoria"),rsRV.getString("proTalla") }); 
            }  
            rsRV.close();
           }   
        catch(SQLException e){
  
            JOptionPane.showMessageDialog(null,"No existen Productos existentes.","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    
    }//GEN-LAST:event_btnVerProductosActionPerformed

    private ResultSet EjecutarQuery(CheckConnection con, String query) throws SQLException {
        PreparedStatement pstm = con.ObtenerConexion().prepareStatement(query);
        ResultSet rsRV = pstm.executeQuery();
        return rsRV;
    }

    private void btnBorrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarProductoActionPerformed

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        
        jF_AñadirProductos.setVisible(true);
        jF_AñadirProductos.setLocationRelativeTo(null);
        
        CheckConnection con = new CheckConnection();
        
        
        try{  
            
            String query = "SELECT COUNT(*) AS Cantidad FROM tblProductos WHERE IDProducto IS NOT NULL";
            ResultSet rsRV = EjecutarQuery(con, query); 
            
            // Crear un JComboBox Para Categorias
            String query2 = "SELECT catNombre FROM tblCategorias";
            ResultSet rsRV2 = EjecutarQuery(con, query2);
            
            List<String> nombresCategorias = new ArrayList<>();
            
            while (rsRV2.next()) {
                String catNombre = rsRV2.getString("catNombre");
                nombresCategorias.add(catNombre);
            }
            rsRV2.close();
            
            // Crear un JComboBox y configurar su modelo de datos con los nombres de las categorías
            DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(nombresCategorias.toArray(new String[0]));
            jCBox_catNombre.setModel(comboBoxModel);
            
            while(rsRV.next())
            { //Extrae del rs y lo añade al Modelo de Tabla     
              int cantidad = rsRV.getInt("Cantidad");
              if (cantidad > 0) {
                  String newid = "PD" + String.format("%03d", cantidad+1);
                  jText_IDProducto.setText(newid);
                  System.out.println(newid);
                } else {
                  String newid = "PD001";
                  jText_IDProducto.setText(newid);
                  System.out.println(newid);

                }
            }    
            rsRV.close();
           }   
        catch(SQLException e){
  
            JOptionPane.showMessageDialog(null,"Hubo un Error en Leer la DB.","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void btnVerCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCategoriasActionPerformed
        jF_VerCategorias.setVisible(true);
        jF_VerCategorias.setLocationRelativeTo(null);
        
        CheckConnection con = new CheckConnection();
           try{ 
            DefaultTableModel tblVerCategorias = new DefaultTableModel(); //Crear Modelo de Tabla 
            tblListaCategorias.setModel(tblVerCategorias);  // Asignar el Modelo de Tabla 
 
            tblVerCategorias.addColumn("IDCategoria"); //Asigna nom,be a cada columna del Modelo de Tabla
            tblVerCategorias.addColumn("Nombre");
     
            String query = "SELECT * FROM tblCategorias";
                        
            ResultSet rsRV = EjecutarQuery(con, query);         
 
            while(rsRV.next())
            { //Extrae del rs y lo añade al Modelo de Tabla     
              tblVerCategorias.addRow(new Object[] {rsRV.getString("IDCategoria"),rsRV.getString("catNombre") }); 
            }  
            rsRV.close();
           }   
        catch(SQLException e){
  
            JOptionPane.showMessageDialog(null,"Hubo Error en Mostrar la Tabla.","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnVerCategoriasActionPerformed

    private void btnNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCategoriaActionPerformed
        jF_AñadirCategoria.setVisible(true);
        jF_AñadirCategoria.setLocationRelativeTo(null);
        
        CheckConnection con = new CheckConnection();
        String query = "SELECT COUNT(*) AS Cantidad FROM tblCategorias WHERE IDCategoria IS NOT NULL";
        
        try{           
            ResultSet rsRV = EjecutarQuery(con, query);         
 
            while(rsRV.next())
            { //Extrae del rs y lo añade al Modelo de Tabla     
              int cantidad = rsRV.getInt("Cantidad");
              if (cantidad > 0) {
                  String newid = "CT" + String.format("%03d", cantidad+1);
                  jText_IDCategoria.setText(newid);
                  System.out.println(newid);
                } else {
                  String newid = "CT001";
                  jText_IDCategoria.setText(newid);
                  System.out.println(newid);

                }
            }  
            rsRV.close();
           }   
        catch(SQLException e){
  
            JOptionPane.showMessageDialog(null,"Hubo un Error en Leer la DB.","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnNuevaCategoriaActionPerformed

    private void btnBorrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarCategoriaActionPerformed

    private void btn_IngresarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarCategoriaActionPerformed
        CheckConnection con = new CheckConnection();
        
        String IDCategoria;
        String catNombre;
        
        try{
              
            IDCategoria = jText_IDCategoria.getText();
            catNombre = jText_catNombre.getText();

            
            Statement st = null;
            st = con.ObtenerConexion().createStatement();
            st.executeUpdate("INSERT INTO tblCategorias (IDCategoria, catNombre)" + " VALUES('" + IDCategoria + "', '" + catNombre + "')");
            
            
            JOptionPane.showMessageDialog(null, "Se registró producto...");
            
            jText_IDCategoria.setText("");
            jText_catNombre.setText("");
            jF_AñadirCategoria.setVisible(false);
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null,"No se Pudo Agregar","Mensaje",JOptionPane.CANCEL_OPTION);
                jText_catNombre.setText("");
        }
    }//GEN-LAST:event_btn_IngresarCategoriaActionPerformed

    private void btnCancelar_NuevoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_NuevoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar_NuevoProdActionPerformed

    private void btnIngresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProductoActionPerformed
        CheckConnection con = new CheckConnection();
        
        String IDProducto;
        String proNombre;
        String proPrecio;
        String IDCategoria = null, catNombre;
        String proTalla;
        
        
        
        
        try{
              
            IDProducto = jText_IDProducto.getText();
            proNombre = jText_proNombre.getText();
            proPrecio = jText_proPrecio.getText();
            proTalla = jText_proTalla.getText();
            catNombre = (String) jCBox_catNombre.getSelectedItem();
            
            String query = "SELECT IDCategoria FROM tblCategorias WHERE catNombre = '"+ catNombre + "'";
            ResultSet rsRV = EjecutarQuery(con, query);  
            
            if (rsRV.next()) {
                IDCategoria = rsRV.getString("IDCategoria");
            }
            
            rsRV.close();
            
            
            Statement st = null;
            st = con.ObtenerConexion().createStatement();
            st.executeUpdate("INSERT INTO tblProductos (IDProducto, proNombre, proPrecio, IDCategoria, proTalla )" + 
                    " VALUES('" + IDProducto + "', '" + proNombre + "', '" + proPrecio + "', '" + IDCategoria + "', '" + proTalla + "')");
            
            
            JOptionPane.showMessageDialog(null, "Se registró producto...");
            
            jText_IDProducto.setText("");
            jText_proNombre.setText("");
            jText_proPrecio.setText("");
            jText_proTalla.setText("");
            jF_AñadirProductos.setVisible(false);
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null,"No se Pudo Agregar","Mensaje",JOptionPane.CANCEL_OPTION);
                jText_catNombre.setText("");
        }
    }//GEN-LAST:event_btnIngresarProductoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProveedorActionPerformed
        jF_AñadirProveedores.setVisible(true);
        jF_AñadirProveedores.setLocationRelativeTo(null);
        
        CheckConnection con = new CheckConnection();
        String query = "SELECT COUNT(*) AS Cantidad FROM tblProveedores WHERE IDProveedor IS NOT NULL";
        
        try{           
            ResultSet rsRV = EjecutarQuery(con, query);         
 
            while(rsRV.next())
            { //Extrae del rs y lo añade al Modelo de Tabla     
              int cantidad = rsRV.getInt("Cantidad");
              if (cantidad > 0) {
                  String newid = "PV" + String.format("%03d", cantidad+1);
                  jText_IDnewProveedor.setText(newid);
                  System.out.println(newid);
                } else {
                  String newid = "PV001";
                  jText_IDnewProveedor.setText(newid);
                  System.out.println(newid);

                }
            }  
            rsRV.close();
           }   
        catch(SQLException e){
  
            JOptionPane.showMessageDialog(null,"Hubo un Error en Leer la DB.","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnNuevoProveedorActionPerformed

    private void btnBorrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarProveedorActionPerformed

    private void btnVerProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProveedoresActionPerformed
        jF_VerProveedores.setVisible(true);
        jF_VerProveedores.setLocationRelativeTo(null);
        
        
        CheckConnection con = new CheckConnection();
           try{ 
            DefaultTableModel tblVerProveedores = new DefaultTableModel(); //Crear Modelo de Tabla 
            tblListaProveedores.setModel(tblVerProveedores);  // Asignar el Modelo de Tabla 
 
            tblVerProveedores.addColumn("IDProveedor"); //Asigna nombre a cada columna del Modelo de Tabla
            tblVerProveedores.addColumn("Nombre");
            tblVerProveedores.addColumn("Contacto");
            tblVerProveedores.addColumn("Nota");
     
            String query = "SELECT * FROM tblProveedores";
                        
            ResultSet rsRV = EjecutarQuery(con, query);         
 
            while(rsRV.next())
            { //Extrae del rs y lo añade al Modelo de Tabla     
              tblVerProveedores.addRow(new Object[] {rsRV.getString("IDProveedor"),rsRV.getString("provNombre"),
                  rsRV.getString("provContacto"),rsRV.getString("provNotas") }); 
            }  
            rsRV.close();
           }   
        catch(SQLException e){
  
            JOptionPane.showMessageDialog(null,"Hubo Error en Mostrar la Tabla.","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnVerProveedoresActionPerformed

    private void btnIngresarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProveedorActionPerformed
        CheckConnection con = new CheckConnection();
        
        String IDProveedor;
        String provNombre;
        String provContacto= null;
        String provNotas = null;

        
        
        
        
        try{
              
            IDProveedor = jText_IDnewProveedor.getText();
            provNombre = jText_provNombre.getText();
            provContacto = jText_provContacto.getText();
            provNotas = jText_provNotas.getText();
            
            Statement st = null;
            st = con.ObtenerConexion().createStatement();
            st.executeUpdate("INSERT INTO tblProveedores (IDProveedor, provNombre, provContacto, provNotas )" + 
                    " VALUES('" + IDProveedor + "', '" + provNombre + "', '" + provContacto + "', '" + provNotas + "')");
            
            
            JOptionPane.showMessageDialog(null, "Se registró producto...");
            
            jText_IDnewProveedor.setText("");
            jText_provNombre.setText("");
            jText_provContacto.setText("");
            jText_provNotas.setText("");
            jF_AñadirProveedores.setVisible(false);
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null,"No se Pudo Agregar","Mensaje",JOptionPane.CANCEL_OPTION);
                jText_catNombre.setText("");
        }
    }//GEN-LAST:event_btnIngresarProveedorActionPerformed

    private void btnCancelar_NuevoprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_NuevoprovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar_NuevoprovActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_onlyTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_onlyTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_onlyTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_onlyTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_onlyTests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane4;
    private javax.swing.JScrollPane JScrollPane5;
    private javax.swing.JScrollPane JScrollPane6;
    private javax.swing.JButton btnBorrarCategoria;
    private javax.swing.JButton btnBorrarProducto;
    private javax.swing.JButton btnBorrarProveedor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar_NuevoProd;
    private javax.swing.JButton btnCancelar_Nuevoprov;
    private javax.swing.JButton btnIngresarProducto;
    private javax.swing.JButton btnIngresarProveedor;
    private javax.swing.JButton btnNuevaCategoria;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnNuevoProveedor;
    private javax.swing.JButton btnVerCategorias;
    private javax.swing.JButton btnVerProductos;
    private javax.swing.JButton btnVerProveedores;
    private javax.swing.JButton btnVerSucursales;
    private javax.swing.JButton btnVerUsuarios;
    private javax.swing.JButton btn_IngresarCategoria;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jCBox_catNombre;
    private javax.swing.JFrame jF_AñadirCategoria;
    private javax.swing.JFrame jF_AñadirProductos;
    private javax.swing.JFrame jF_AñadirProveedores;
    private javax.swing.JFrame jF_VerCategorias;
    private javax.swing.JFrame jF_VerProductos;
    private javax.swing.JFrame jF_VerProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_listaProveedores;
    private javax.swing.JLabel jLabel_listaTallas;
    private javax.swing.JLabel jLabel_listaTallas1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jText_IDCategoria;
    private javax.swing.JTextField jText_IDProducto;
    private javax.swing.JTextField jText_IDnewProveedor;
    private javax.swing.JTextField jText_catNombre;
    private javax.swing.JTextField jText_proNombre;
    private javax.swing.JTextField jText_proPrecio;
    private javax.swing.JTextField jText_proTalla;
    private javax.swing.JTextField jText_provContacto;
    private javax.swing.JTextField jText_provNombre;
    private javax.swing.JTextField jText_provNotas;
    private javax.swing.JTable tblListaCategorias;
    private javax.swing.JTable tblListaProductos;
    private javax.swing.JTable tblListaProveedores;
    // End of variables declaration//GEN-END:variables
}
